# proto-file: proto/templated_plugin_tests.proto
# proto-message: TemplatedPluginTests

config: {
  tested_plugin: "MLFlow_CVE_2023_6014"
}

tests: {
  name: "whenMLFlowVulnerable_returnsTrue"
  expect_vulnerability: true

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 401
        body_content: 'You are not authenticated. Please see https://www.mlflow.org/docs/latest/auth/index.html#authenticating-to-mlflow on how to authenticate.'
      },
      {
        uri: "/api/2.0/mlflow/users/create"
        status: 200
        body_content: '... Successfully signed up user: ...'
      }
    ]
  }
}

tests: {
  name: "whenMLFlowNotVulnerable_returnsFalse"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri: "/"
        status: 401
        body_content: 'You are not authenticated. Please see https://www.mlflow.org/docs/latest/auth/index.html#authenticating-to-mlflow on how to authenticate.'
      },
      {
        uri: "/api/2.0/mlflow/users/create"
        status: 401
        body_content: '... error ...'
      }
    ]
  }
}

tests: {
  name: "whenNotMLFlow_returnsFalse"
  expect_vulnerability: false

  mock_http_server: {
    mock_responses: [
      {
        uri: "TSUNAMI_MAGIC_ANY_URI"
        status: 200
        body_content: "Login to your Drupal account"
      }
    ]
  }
}
